// Typing lessons data structure - Beginner to Advanced
export interface Lesson {
  id: string;
  level: "beginner" | "intermediate" | "advanced";
  language: "english" | "hindi";
  title: string;
  description: string;
  topic: string;
  texts: string[];
  minWpm: number;
  minAccuracy: number;
  estimatedTime: number; // in seconds
  difficulty: number; // 1-10 scale
}

export const typingLessons: Lesson[] = [
  // ENGLISH BEGINNER LESSONS
  {
    id: "en-beginner-1",
    level: "beginner",
    language: "english",
    title: "Home Row Keys",
    description: "Learn the fundamental home row keys (asdf jkl;)",
    topic: "Home Row Foundation",
    texts: [
      "ads dad all fall hall fall jad jak lad",
      "flask flasks ask asks sad fads falls jads",
      "add adds half halfs ask asks lads lashes",
    ],
    minWpm: 15,
    minAccuracy: 90,
    estimatedTime: 60,
    difficulty: 1,
  },
  {
    id: "en-beginner-2",
    level: "beginner",
    language: "english",
    title: "Top Row Introduction",
    description: "Introduce top row keys with home row practice",
    topic: "Expanding Keys",
    texts: [
      "tea eat seat feet tea sale tale fate sale",
      "steal steal steel feast feast seat eats test",
      "taste fate gate late fast east test sets get",
    ],
    minWpm: 16,
    minAccuracy: 90,
    estimatedTime: 75,
    difficulty: 2,
  },
  {
    id: "en-beginner-3",
    level: "beginner",
    language: "english",
    title: "Bottom Row Foundation",
    description: "Practice bottom row keys (bnm cvxz)",
    topic: "Complete Key Coverage",
    texts: [
      "van ban can man men ben net ten den end",
      "bench bunch bunch bunch mend mends bend bends",
      "come zoom zoom zoom come come come come come",
    ],
    minWpm: 17,
    minAccuracy: 90,
    estimatedTime: 90,
    difficulty: 2,
  },
  {
    id: "en-beginner-4",
    level: "beginner",
    language: "english",
    title: "Common Words",
    description: "Type common English words and simple sentences",
    topic: "Vocabulary Building",
    texts: [
      "the and for are but not you all can had her was one our out day get has him his how its may new now see two way who boy did its let may old see she too use",
      "A cat sat on the mat and fell asleep fast",
      "The sun is very hot today in the city",
    ],
    minWpm: 18,
    minAccuracy: 90,
    estimatedTime: 120,
    difficulty: 3,
  },
  {
    id: "en-beginner-5",
    level: "beginner",
    language: "english",
    title: "Simple Sentences",
    description: "Type simple sentences with basic punctuation",
    topic: "Sentence Formation",
    texts: [
      "I like to read books. She goes to school. He plays football every day.",
      "The quick brown fox jumps. A cat sat on mat. Dogs like to play outside.",
      "I love typing practice. It is very helpful. My speed is improving fast.",
    ],
    minWpm: 20,
    minAccuracy: 92,
    estimatedTime: 150,
    difficulty: 4,
  },

  // ENGLISH INTERMEDIATE LESSONS
  {
    id: "en-intermediate-1",
    level: "intermediate",
    language: "english",
    title: "Speed Building",
    description: "Focus on maintaining accuracy while increasing speed",
    topic: "Velocity Training",
    texts: [
      "Success is not final, failure is not fatal: it is the courage to continue that counts.",
      "The only way to do great work is to love what you do every single day in life.",
      "Innovation distinguishes between a leader and a follower in modern business world.",
    ],
    minWpm: 25,
    minAccuracy: 95,
    estimatedTime: 120,
    difficulty: 5,
  },
  {
    id: "en-intermediate-2",
    level: "intermediate",
    language: "english",
    title: "Professional Content",
    description: "Type business and professional documents",
    topic: "Corporate Writing",
    texts: [
      "In today's competitive business environment, effective communication is paramount to success.",
      "Productivity and efficiency have become key metrics in measuring organizational performance.",
      "Technology continues to revolutionize the way we work and communicate globally.",
    ],
    minWpm: 26,
    minAccuracy: 95,
    estimatedTime: 135,
    difficulty: 6,
  },
  {
    id: "en-intermediate-3",
    level: "intermediate",
    language: "english",
    title: "Technical Writing",
    description: "Master complex words and technical terminology",
    topic: "Specialized Vocabulary",
    texts: [
      "Implementing comprehensive algorithms requires understanding fundamental data structures thoroughly.",
      "Optimization techniques significantly enhance system performance and resource utilization efficiency.",
      "Database management systems require careful architectural planning and scalability considerations.",
    ],
    minWpm: 27,
    minAccuracy: 95,
    estimatedTime: 150,
    difficulty: 7,
  },
  {
    id: "en-intermediate-4",
    level: "intermediate",
    language: "english",
    title: "Long Form Accuracy",
    description: "Extended passages with high accuracy requirements",
    topic: "Endurance Training",
    texts: [
      "The pursuit of excellence in any endeavor requires dedication, discipline, and unwavering commitment to continuous improvement.",
      "Digital transformation has fundamentally altered business operations, customer relationships, and organizational strategies globally.",
      "Educational technology platforms are revolutionizing learning methodologies and democratizing access to quality education worldwide.",
    ],
    minWpm: 28,
    minAccuracy: 96,
    estimatedTime: 180,
    difficulty: 8,
  },

  // ENGLISH ADVANCED LESSONS
  {
    id: "en-advanced-1",
    level: "advanced",
    language: "english",
    title: "Expert Velocity",
    description: "High-speed practice with complex vocabulary",
    topic: "Maximum Speed Achievement",
    texts: [
      "Technological advancements have exponentially accelerated the pace of innovation across virtually every industry sector globally.",
      "Multidisciplinary approaches to problem-solving facilitate comprehensive analysis and implementation of sustainable solutions systematically.",
      "Organizational transformation necessitates fundamental reimagining of operational frameworks and strategic positioning methodologies.",
    ],
    minWpm: 35,
    minAccuracy: 98,
    estimatedTime: 120,
    difficulty: 9,
  },
  {
    id: "en-advanced-2",
    level: "advanced",
    language: "english",
    title: "Literary Excellence",
    description: "Complex literary and academic passages",
    topic: "Sophisticated Content",
    texts: [
      "The intricate interplay between consciousness and external circumstances perpetually shapes human experience and philosophical understanding profoundly.",
      "Epistemological considerations regarding knowledge acquisition fundamentally challenge conventional assumptions about cognitive processes and perception mechanisms.",
      "Sociological frameworks examining contemporary culture illuminate complex dynamics underlying human behavior and institutional structures systematically.",
    ],
    minWpm: 36,
    minAccuracy: 98,
    estimatedTime: 150,
    difficulty: 10,
  },

  // HINDI BEGINNER LESSONS
  {
    id: "hi-beginner-1",
    level: "beginner",
    language: "hindi",
    title: "मुख्य व्यंजन",
    description: "मुख्य व्यंजन (क से म) का अभ्यास करें",
    topic: "आधार व्यंजन",
    texts: [
      "क ख ग घ च छ ज झ ट ठ ड ढ त थ द ध न प फ ब भ म य र ल व",
      "क क क ख ख ख ग ग ग घ घ घ च च च छ छ छ",
      "कक खख गग घघ चच छछ जज झझ टट ठठ",
    ],
    minWpm: 12,
    minAccuracy: 85,
    estimatedTime: 60,
    difficulty: 1,
  },
  {
    id: "hi-beginner-2",
    level: "beginner",
    language: "hindi",
    title: "सरल शब्द",
    description: "सरल हिंदी शब्दों का अभ्यास",
    topic: "शब्द निर्माण",
    texts: [
      "कम कामकाज कान काठ किताब किला किस्म कुछ कूड़ा कूद",
      "खाना खड़ा खेल खून खटमल खिचड़ी खिड़की खिलाड़ी",
      "गाय गाड़ी गली गहरा गदहा गधा गिनती गिरना गिरफ्तार",
    ],
    minWpm: 13,
    minAccuracy: 85,
    estimatedTime: 90,
    difficulty: 2,
  },
  {
    id: "hi-beginner-3",
    level: "beginner",
    language: "hindi",
    title: "दैनिक शब्दावली",
    description: "रोज़मर्रा के हिंदी शब्द और मुहावरे",
    topic: "दैनिक जीवन",
    texts: [
      "सुबह उठना नहा धोना नाश्ता करना स्कूल जाना",
      "माता पिता भाई बहन दादा दादी नाना नानी",
      "घर दरवाज़ा खिड़की छत दीवार फर्श सीढ़ी बालकनी",
    ],
    minWpm: 15,
    minAccuracy: 88,
    estimatedTime: 120,
    difficulty: 3,
  },
  {
    id: "hi-beginner-4",
    level: "beginner",
    language: "hindi",
    title: "सरल वाक्य",
    description: "हिंदी में सरल वाक्य लेखन",
    topic: "वाक्य निर्माण",
    texts: [
      "मेरा नाम राज है। मैं स्कूल जाता हूँ। आज मौसम बहुत अच्छा है।",
      "मुझे किताबें पढ़ना बहुत पसंद है। मेरा घर शहर के पास है।",
      "पक्षी आसमान में उड़ते हैं। फूल बहुत सुंदर होते हैं।",
    ],
    minWpm: 17,
    minAccuracy: 90,
    estimatedTime: 150,
    difficulty: 4,
  },
  {
    id: "hi-beginner-5",
    level: "beginner",
    language: "hindi",
    title: "संयुक्त शब्द",
    description: "संयुक्त व्यंजन और जटिल शब्द",
    topic: "उन्नत शब्दावली",
    texts: [
      "क्षेत्र क्षितिज क्षमता क्षय क्षारीय प्रिय प्रश्न प्रसन्न प्रहार",
      "श्रीमान श्रीमती श्रमिक श्रांत श्रृंगार ज्ञान ज्ञानी",
      "विद्यालय विद्यार्थी विज्ञान विमान विवाद विलास विषय",
    ],
    minWpm: 19,
    minAccuracy: 92,
    estimatedTime: 180,
    difficulty: 5,
  },

  // HINDI INTERMEDIATE LESSONS
  {
    id: "hi-intermediate-1",
    level: "intermediate",
    language: "hindi",
    title: "गद्य अभ्यास",
    description: "सार्थक हिंदी अनुच्छेद टाइपिंग",
    topic: "लंबे पाठ",
    texts: [
      "शिक्षा मनुष्य के विकास का मूल आधार है। यह हमारे ज्ञान, कौशल और व्यक्तित्व को निखारती है।",
      "हमारा भारत देश बहुत सुंदर है। यहाँ विविध संस्कृतियों का मिलन होता है।",
      "पुस्तकें मानव की सबसे अच्छी मित्र हैं। ये हमें ज्ञान और आनंद प्रदान करती हैं।",
    ],
    minWpm: 20,
    minAccuracy: 94,
    estimatedTime: 120,
    difficulty: 6,
  },
  {
    id: "hi-intermediate-2",
    level: "intermediate",
    language: "hindi",
    title: "साहित्यिक सामग्री",
    description: "काव्य और साहित्यिक हिंदी",
    topic: "साहित्य",
    texts: [
      "कविता भावनाओं की अभिव्यक्ति का सबसे सुंदर माध्यम है। कवि अपने विचारों को शब्दों में बाँधते हैं।",
      "भारतीय साहित्य विश्व के सबसे समृद्ध साहित्य में से एक है। तुलसीदास और कालिदास महान कवि थे।",
    ],
    minWpm: 22,
    minAccuracy: 95,
    estimatedTime: 135,
    difficulty: 7,
  },
  {
    id: "hi-intermediate-3",
    level: "intermediate",
    language: "hindi",
    title: "तकनीकी हिंदी",
    description: "वैज्ञानिक और तकनीकी शब्दावली",
    topic: "विशेष पाठ",
    texts: [
      "कंप्यूटर आधुनिक तकनीक का एक महत्वपूर्ण उपकरण है। इंटरनेट ने विश्व को जोड़ दिया है।",
      "विज्ञान और प्रौद्योगिकी का विकास मानव समाज को आगे ले जाता है।",
    ],
    minWpm: 24,
    minAccuracy: 95,
    estimatedTime: 150,
    difficulty: 8,
  },

  // HINDI ADVANCED LESSONS
  {
    id: "hi-advanced-1",
    level: "advanced",
    language: "hindi",
    title: "उच्च स्तरीय पाठ",
    description: "जटिल और विस्तृत हिंदी पाठ",
    topic: "उन्नत लेखन",
    texts: [
      "राष्ट्रीय विकास और सामाजिक प्रगति के लिए शिक्षा, स्वास्थ्य और तकनीकी कौशल आवश्यक है।",
      "भारतीय संस्कृति की गहरी जड़ें ज्ञान, कला और आध्यात्मिकता में निहित हैं।",
    ],
    minWpm: 28,
    minAccuracy: 97,
    estimatedTime: 120,
    difficulty: 9,
  },
  {
    id: "hi-advanced-2",
    level: "advanced",
    language: "hindi",
    title: "विशेषज्ञ स्तर",
    description: "सर्वोच्च स्तर की हिंदी टाइपिंग",
    topic: "परीक्षा स्तर",
    texts: [
      "सामाजिक परिवर्तन का दायित्व प्रत्येक नागरिक का है। शिक्षा और जागरूकता का प्रसार समाज के विकास का मूल मंत्र है।",
      "पर्यावरण संरक्षण और सतत विकास आधुनिक युग की प्रमुख चुनौतियाँ हैं।",
    ],
    minWpm: 30,
    minAccuracy: 99,
    estimatedTime: 150,
    difficulty: 10,
  },

  // SIMPLE WORDS LESSONS - ENGLISH
  {
    id: "en-simple-words-1",
    level: "beginner",
    language: "english",
    title: "Simple 2-Letter Words",
    description: "Learn and practice simple 2-letter words",
    topic: "Word Building",
    texts: [
      "at an as be by do go he if in is it me my no of on or so to up us we",
      "at be do go he is it me no of or so to up we",
      "am as by go he if in it my no on or to up us we",
    ],
    minWpm: 14,
    minAccuracy: 92,
    estimatedTime: 60,
    difficulty: 1,
  },
  {
    id: "en-simple-words-2",
    level: "beginner",
    language: "english",
    title: "Simple 3-Letter Words",
    description: "Practice common 3-letter words",
    topic: "Word Practice",
    texts: [
      "the and for are but not you all can had her was one our out day get has him his",
      "cat dog bat hat sat mat fat rat car bus toy box pen map key cup tea bed",
      "and but for not you all can get has had her him his day out one two",
    ],
    minWpm: 15,
    minAccuracy: 92,
    estimatedTime: 90,
    difficulty: 2,
  },
  {
    id: "en-simple-words-3",
    level: "beginner",
    language: "english",
    title: "Body Parts",
    description: "Type words related to body parts",
    topic: "Vocabulary",
    texts: [
      "head eye ear nose face hair chin lips teeth mouth tongue jaw neck",
      "arm hand finger thumb wrist elbow shoulder chest back stomach belly",
      "leg foot knee ankle toe thigh hip skin bone blood heart brain",
    ],
    minWpm: 16,
    minAccuracy: 91,
    estimatedTime: 90,
    difficulty: 2,
  },
  {
    id: "en-simple-words-4",
    level: "beginner",
    language: "english",
    title: "Animals",
    description: "Type names of common animals",
    topic: "Animals",
    texts: [
      "cat dog bird fish cow sheep goat pig hen duck elephant lion tiger bear",
      "butterfly ant bee mosquito fly spider snake crocodile frog turtle",
      "horse donkey camel zebra giraffe cheetah leopard wolf fox rabbit squirrel",
    ],
    minWpm: 17,
    minAccuracy: 91,
    estimatedTime: 105,
    difficulty: 2,
  },
  {
    id: "en-simple-words-5",
    level: "beginner",
    language: "english",
    title: "Colors",
    description: "Practice color names",
    topic: "Colors",
    texts: [
      "red blue green yellow orange purple pink brown black white gray silver",
      "red orange yellow green blue indigo violet pink brown black white",
      "light dark bright pale golden silver bronze copper navy cream beige",
    ],
    minWpm: 16,
    minAccuracy: 93,
    estimatedTime: 75,
    difficulty: 2,
  },
  {
    id: "en-simple-words-6",
    level: "beginner",
    language: "english",
    title: "Food Items",
    description: "Type common food and drink words",
    topic: "Food",
    texts: [
      "apple banana orange mango grape watermelon strawberry blueberry pear peach",
      "rice bread milk cheese butter egg meat fish chicken fish beef pork",
      "rice wheat corn beans lentil pea carrot potato onion garlic tomato",
    ],
    minWpm: 17,
    minAccuracy: 90,
    estimatedTime: 105,
    difficulty: 2,
  },
  {
    id: "en-simple-words-7",
    level: "beginner",
    language: "english",
    title: "Daily Objects",
    description: "Type names of everyday objects",
    topic: "Objects",
    texts: [
      "table chair desk bed sofa lamp clock radio phone computer television",
      "pen pencil paper book notebook cup glass plate bowl spoon fork knife",
      "door window wall floor roof carpet rug blanket pillow sheet towel",
    ],
    minWpm: 18,
    minAccuracy: 90,
    estimatedTime: 120,
    difficulty: 3,
  },
  {
    id: "en-simple-words-8",
    level: "beginner",
    language: "english",
    title: "Weather Words",
    description: "Type weather-related vocabulary",
    topic: "Weather",
    texts: [
      "sunny rainy cloudy windy stormy snowy foggy humid hot cold cool warm",
      "rain snow hail sleet frost dew mist cloud fog thunder lightning wind",
      "sun moon star sky day night dawn dusk twilight sunshine moonlight",
    ],
    minWpm: 16,
    minAccuracy: 91,
    estimatedTime: 105,
    difficulty: 2,
  },
  {
    id: "en-simple-words-9",
    level: "beginner",
    language: "english",
    title: "Numbers and Time",
    description: "Practice numbers and time-related words",
    topic: "Numbers",
    texts: [
      "one two three four five six seven eight nine ten eleven twelve",
      "monday tuesday wednesday thursday friday saturday sunday january february march",
      "morning afternoon evening night midnight noon hour minute second today tomorrow",
    ],
    minWpm: 16,
    minAccuracy: 92,
    estimatedTime: 105,
    difficulty: 2,
  },
  {
    id: "en-simple-words-10",
    level: "beginner",
    language: "english",
    title: "Action Words",
    description: "Type common action verbs",
    topic: "Verbs",
    texts: [
      "run walk jump sit stand sleep eat drink read write speak listen play",
      "run walk jump swim fly drive go come see watch look hear listen talk",
      "eat drink sleep wake play laugh cry smile dance sing draw paint write",
    ],
    minWpm: 17,
    minAccuracy: 91,
    estimatedTime: 120,
    difficulty: 3,
  },

  // SIMPLE WORDS LESSONS - HINDI
  {
    id: "hi-simple-words-1",
    level: "beginner",
    language: "hindi",
    title: "सरल दो अक्षर शब्द",
    description: "दो अक्षर वाले सरल शब्दों का अभ्यास",
    topic: "आधार शब्द",
    texts: [
      "का की कु के कम कर कह कब कोई काठ कान",
      "गा गो गु गड़ गीत गुलाब गार्डन गांव गली गुड़",
      "चा चल चम चाँद चाय चेहरा चित्र चोर चूल्हा",
    ],
    minWpm: 14,
    minAccuracy: 88,
    estimatedTime: 90,
    difficulty: 2,
  },
  {
    id: "hi-simple-words-2",
    level: "beginner",
    language: "hindi",
    title: "शरीर के अंग",
    description: "शरीर के विभिन्न हिस्सों के नाम",
    topic: "शरीर",
    texts: [
      "सिर आँख कान नाक चेहरा बाल ठुड्डी होंठ दाँत जीभ",
      "हाथ उँगली अँगूठा कलाई कोहनी कंधा छाती पीठ पेट",
      "पैर पँजा घुटना टखना जाँघ कूल्हा त्वचा हड्डी खून दिल",
    ],
    minWpm: 15,
    minAccuracy: 87,
    estimatedTime: 105,
    difficulty: 2,
  },
  {
    id: "hi-simple-words-3",
    level: "beginner",
    language: "hindi",
    title: "जानवर के नाम",
    description: "आम जानवरों के हिंदी नाम",
    topic: "जानवर",
    texts: [
      "बिल्ली कुत्ता पक्षी मछली गाय भेड़ बकरा सूअर मुर्गी बतख",
      "हाथी शेर बाघ भालू भेड़िया लोमड़ी खरगोश गिलहरी साँप मगरमच्छ",
      "तितली चींटी मधुमक्खी मच्छर मक्खी मकड़ी केकड़ा केंचुआ बिच्छू",
    ],
    minWpm: 16,
    minAccuracy: 87,
    estimatedTime: 120,
    difficulty: 2,
  },
  {
    id: "hi-simple-words-4",
    level: "beginner",
    language: "hindi",
    title: "रंग के नाम",
    description: "विभिन्न रंगों के हिंदी नाम",
    topic: "रंग",
    texts: [
      "लाल नीला हरा पीला नारंगी बैंगनी गुलाबी भूरा काला सफेद",
      "लाल गुलाबी सफेद काला हरा पीला नीला बैंगनी नारंगी भूरा",
      "सुनहरा चाँदी का रंग तांबा रंग ताँबा पीतल रंग गहरा हल्का",
    ],
    minWpm: 15,
    minAccuracy: 89,
    estimatedTime: 90,
    difficulty: 2,
  },
  {
    id: "hi-simple-words-5",
    level: "beginner",
    language: "hindi",
    title: "खाने की चीजें",
    description: "खाद्य पदार्थों के नाम",
    topic: "खाना",
    texts: [
      "सेब केला संतरा आम अंगूर तरबूज़ स्ट्रॉबेरी ब्लूबेरी नाशपाती",
      "चावल रोटी दूध पनीर मक्खन अंडा मांस मछली चिकन गोमांस",
      "चावल गेहूँ मक्का दालें मटर गाजर आलू प्याज़ लहसुन टमाटर",
    ],
    minWpm: 16,
    minAccuracy: 88,
    estimatedTime: 120,
    difficulty: 2,
  },
  {
    id: "hi-simple-words-6",
    level: "beginner",
    language: "hindi",
    title: "रोज़मर्रा की वस्तुएँ",
    description: "दैनिक उपयोग की चीजों के नाम",
    topic: "वस्तुएँ",
    texts: [
      "मेज़ कुर्सी डेस्क बिस्तर सोफा लैम्प घड़ी रेडियो फोन कंप्यूटर",
      "कलम पेंसिल कागज़ किताब नोटबुक कप गिलास प्लेट कटोरी चम्मच",
      "दरवाज़ा खिड़की दीवार फर्श छत कालीन रग कंबल तकिया चादर",
    ],
    minWpm: 16,
    minAccuracy: 87,
    estimatedTime: 120,
    difficulty: 2,
  },
  {
    id: "hi-simple-words-7",
    level: "beginner",
    language: "hindi",
    title: "मौसम के शब्द",
    description: "मौसम संबंधी शब्दावली",
    topic: "मौसम",
    texts: [
      "धूप बारिश बादल हवा तूफान बर्फ़ कोहरा नम गर्म ठंडा ठंडक",
      "वर्षा हिम ओले वर्षा कणिकाएँ पाला ओस कुहरा बादल कोहरा बयार",
      "सूरज चाँद तारा आसमान दिन रात भोर संध्या गोधूलि धूप चाँदनी",
    ],
    minWpm: 15,
    minAccuracy: 88,
    estimatedTime: 105,
    difficulty: 2,
  },
  {
    id: "hi-simple-words-8",
    level: "beginner",
    language: "hindi",
    title: "संख्याएँ और समय",
    description: "संख्याओं और समय संबंधी शब्द",
    topic: "संख्याएँ",
    texts: [
      "एक दो तीन चार पाँच छः सात आठ नौ दस ग्यारह बारह",
      "सोमवार मंगलवार बुधवार गुरुवार शुक्रवार शनिवार रविवार जनवरी फरवरी",
      "सुबह दोपहर शाम रात आधी रात दोपहर घंटा मिनट सेकंड आज कल",
    ],
    minWpm: 15,
    minAccuracy: 90,
    estimatedTime: 105,
    difficulty: 2,
  },
  {
    id: "hi-simple-words-9",
    level: "beginner",
    language: "hindi",
    title: "क्रिया शब्द",
    description: "आम क्रिया शब्दों का अभ्यास",
    topic: "क्रिया",
    texts: [
      "दौड़ना चलना कूदना बैठना खड़ा होना सोना खाना पीना पढ़ना लिखना",
      "दौड़ना चलना कूदना तैरना उड़ना गाड़ी चलाना जाना आना देखना सुनना",
      "खाना पीना सोना जागना खेलना हँसना रोना मुस्कुराना नाचना गाना",
    ],
    minWpm: 16,
    minAccuracy: 89,
    estimatedTime: 120,
    difficulty: 2,
  },
  {
    id: "hi-simple-words-10",
    level: "beginner",
    language: "hindi",
    title: "विशेषण शब्द",
    description: "आम विशेषण शब्दों का अभ्यास",
    topic: "विशेषण",
    texts: [
      "बड़ा छोटा लंबा चौड़ा ऊँचा गहरा हल्का भारी तेज़ धीमा तीव्र सुंदर",
      "अच्छा बुरा सुंदर बदसूरत चमकदार फीका गर्म ठंडा मीठा नमकीन खट्टा",
      "नया पुराना स्वच्छ गंदा शांत शोरगुल वाला साफ़ मैली उज्ज्वल अंधकार",
    ],
    minWpm: 16,
    minAccuracy: 88,
    estimatedTime: 120,
    difficulty: 3,
  },
];

// Get lessons by language and level
export function getLessonsByLanguageAndLevel(
  language: "english" | "hindi",
  level: "beginner" | "intermediate" | "advanced"
): Lesson[] {
  return typingLessons.filter(
    (lesson) => lesson.language === language && lesson.level === level
  );
}

// Get all lessons for a language
export function getLessonsByLanguage(
  language: "english" | "hindi"
): Lesson[] {
  return typingLessons.filter((lesson) => lesson.language === language);
}

// Calculate total difficulty score
export function calculateDifficultyScore(lessons: Lesson[]): number {
  if (lessons.length === 0) return 0;
  return Math.round(
    lessons.reduce((sum, lesson) => sum + lesson.difficulty, 0) /
      lessons.length
  );
}
